const Do = {
  ADD_DECK: 'ADD_DECK',
  GET_DECK: 'GET_DECK',
  ADD_QUESTION: 'ADD_QUESTION',
  QUESTIONS: 'QUESTIONS',
  DECKS: 'DECKS',
  SCORES: 'SCORES',
  QUIZ_SCORE: 'QUIZ_SCORE',
  CORRECT_ANSWER: 'CORRECT_ANSWER',
  SETUP_QUIZ: 'SETUP_QUIZ',
  RESET_QUIZ: 'RESET_QUIZ',
  QUESTION_INDEX: 'QUESTION_INDEX',
  STORE_SCORE: 'STORE_SCORE'
}

export default Do